# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enables dynamic lighting of firefly particles from Firefly Bushes.
	firefly = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				zombie = true
				ender_pearl = true
				item_display = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				block_display = true
				tnt_minecart = true
				zombie_villager = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				witch = true
				cod = true
				snow_golem = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				vex = true
				wandering_trader = true
				wither_skeleton = true
				piglin_brute = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.tconstruct]
				indestructible_item = true
				flint_shuriken = true
				fluid_spit = true
				ender_slime = true
				crystalshot = true
				glow_ball = true
				terracube = true
				fancy_item_frame = true
				sky_slime = true
				efln_ball = true
				quartz_shuriken = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.lucky]
				lucky_potion = true
				lucky_projectile = true
				delayed_drop = true

			[light_sources.settings.entities.alexscaves]
				gammaroach = true
				caniac = true
				thrown_ice_cream_scoop = true
				lanternfish = true
				thrown_waste_drum = true
				seeking_arrow = true
				forsaken = true
				tremorzilla = true
				falling_guano = true
				ink_bomb = true
				atlatitan = true
				cinder_brick = true
				moving_metal_block = true
				trilocaris = true
				sugar_staff_hex = true
				teletor = true
				watcher = true
				spinning_peppermint = true
				quarry_smasher = true
				gumbeeper = true
				caramel_cube = true
				candicorn = true
				soda_bottle_rocket = true
				tephra = true
				brainiac = true
				falling_tree_block = true
				notor = true
				depth_charge = true
				magnetron = true
				corrodent = true
				crushed_block = true
				sweetish_fish = true
				extinction_spear = true
				hullbreaker = true
				luxtructosaurus = true
				deep_one_mage = true
				dark_arrow = true
				gum_worm_segment = true
				gumball = true
				radgill = true
				underzealot = true
				wave = true
				magnetic_weapon = true
				submarine = true
				gummy_bear = true
				licowitch = true
				guano = true
				gum_worm = true
				sea_pig = true
				floater = true
				vesper = true
				beholder_eye = true
				dinosaur_spirit = true
				ferrouslime = true
				candy_cane_hook = true
				desolate_dagger = true
				melted_caramel = true
				water_bolt = true
				limestone_spear = true
				boundroid_winch = true
				deep_one_knight = true
				tripodfish = true
				subterranodon = true
				gossamer_worm = true
				deep_one = true
				gloomoth = true
				nucleeper = true
				mine_guardian = true
				burrowing_arrow = true
				mine_guardian_anchor = true
				chest_boat = true
				nuclear_explosion = true
				boat = true
				boundroid = true
				falling_frostmint = true
				vallumraptor = true
				grottoceratops = true
				tremorsaurus = true
				relicheirus = true
				raycat = true
				gingerbread_man = true
				frostmint_spear = true
				nuclear_bomb = true

			[light_sources.settings.entities.mowziesmobs]
				umvuthana_crane = true
				umvuthana_raptor = true
				frozen_controller = true
				poison_ball = true
				ferrous_wroughtnaut = true
				baby_foliaath = true
				umvuthi = true
				dart = true
				axe_attack = true
				sunstrike = true
				ice_ball = true
				foliaath = true
				boulder_platform = true
				fissure = true
				ice_breath = true
				rock_sling = true
				umvuthana_follower_player = true
				super_nova = true
				block_swapper = true
				boulder_projectile = true
				umvuthana_follower_raptor = true
				umvuthana = true
				pillar_piece = true
				frostmaw = true
				earth_spike = true
				lantern = true
				pillar_sculptor = true
				camera_shake = true
				block_swapper_tunneling = true
				falling_block = true
				fissure_piece = true
				sculptor = true
				pillar = true
				boulder_platform_crumbling = true
				solar_beam = true
				bluff = true
				grottol = true
				naga = true
				umvuthana_crane_player = true

			[light_sources.settings.entities.alexsmobs]
				devils_hole_pupfish = true
				kangaroo = true
				blue_jay = true
				skelewag = true
				bone_serpent_part = true
				catfish = true
				tasmanian_devil = true
				fart = true
				centipede_tail = true
				cosmic_cod = true
				rhinoceros = true
				comb_jelly = true
				jerboa = true
				mungus = true
				vine_lasso = true
				skunk = true
				bunfungus = true
				dropbear = true
				rattlesnake = true
				blobfish = true
				mimicube = true
				snow_leopard = true
				moose = true
				tiger = true
				rocky_roller = true
				rain_frog = true
				cosmaw = true
				mosquito_spit = true
				stradpole = true
				spectre = true
				hemolymph = true
				anaconda = true
				hammerhead_shark = true
				sunbird = true
				triops = true
				gazelle = true
				sea_bear = true
				tarantula_hawk = true
				void_worm_part = true
				void_worm_shot = true
				enderiophage = true
				void_portal = true
				terrapin = true
				platypus = true
				murmur = true
				void_worm = true
				centipede_body = true
				bald_eagle = true
				froststalker = true
				fly = true
				toucan = true
				skreecher = true
				cachalot_whale = true
				tossed_item = true
				bison = true
				pollen_ball = true
				mudskipper = true
				mud_ball = true
				gelada_monkey = true
				murmur_head = true
				cachalot_echo = true
				anteater = true
				laviathan = true
				enderiophage_rocket = true
				endergrade = true
				roadrunner = true
				cockroach_egg = true
				leafcutter_ant = true
				shoebill = true
				lobster = true
				grizzly_bear = true
				squid_grapple = true
				farseer = true
				potoo = true
				centipede_head = true
				flutter = true
				orca = true
				tendon_segment = true
				ice_shard = true
				maned_wolf = true
				crow = true
				banana_slug = true
				elephant = true
				crocodile = true
				crimson_mosquito = true
				sand_shot = true
				seal = true
				straddler = true
				emu = true
				mimic_octopus = true
				soul_vulture = true
				warped_mosco = true
				guster = true
				caiman = true
				tusklin = true
				underminer = true
				anaconda_part = true
				emu_egg = true
				gorilla = true
				flying_fish = true
				capuchin_monkey = true
				cockroach = true
				komodo_dragon = true
				bone_serpent = true
				mantis_shrimp = true
				seagull = true
				raccoon = true
				alligator_snapping_turtle = true
				giant_squid = true
				hummingbird = true
				straddleboard = true
				frilled_shark = true
				warped_toad = true
				shark_tooth_arrow = true
				gust = true
				sugar_glider = true

			[light_sources.settings.entities.mutantmonsters]
				mutant_enderman = true
				mutant_creeper = true
				creeper_minion = true
				creeper_minion_egg = true
				mutant_zombie = true
				skull_spirit = true
				endersoul_clone = true
				throwable_block = true
				spider_pig = true
				mutant_snow_golem = true
				endersoul_fragment = true
				mutant_skeleton = true
				body_part = true
				mutant_arrow = true

			[light_sources.settings.entities.mca]
				grim_reaper = true
				male_zombie_villager = true
				crib = true
				female_zombie_villager = true
				female_villager = true
				male_villager = true

			[light_sources.settings.entities.deeperdarker]
				shattered = true
				sludge = true
				stalker = true
				shriek_worm = true
				sculk_centipede = true
				sculk_leech = true
				chest_boat = true
				angler_fish = true
				boat = true
				sculk_snapper = true

			[light_sources.settings.entities.tacz]
				target_minecart = true
				bullet = true

			[light_sources.settings.entities.trials]
				wind_charge = true
				bogged = true
				breeze = true

			[light_sources.settings.entities.betternether]
				naga_projectile = true
				firefly = true
				flying_pig = true
				hydrogen_jellyfish = true
				jungle_skeleton = true
				skull = true
				naga = true

			[light_sources.settings.entities.bclib]
				chair = true

			[light_sources.settings.entities.quark]
				quark_boat = true
				dyed_item_frame = true
				stool = true
				skull_pike = true
				toretoise = true
				gravisand = true
				parrot_egg = true
				stoneling = true
				foxhound = true
				torch_arrow = true
				wraith = true
				shiba = true
				totem = true
				forgotten = true
				quark_chest_boat = true
				glass_frame = true
				crab = true
				pickarang = true
				soul_bead = true
				flamerang = true

			[light_sources.settings.entities.supplementaries]
				dispenser_minecart = true
				slingshot_projectile = true
				brick_projectile = true
				falling_sack = true
				pearl_marker = true
				hat_stand = true
				bomb = true
				falling_ash = true
				cannonball = true
				falling_urn = true
				red_merchant = true
				rope_arrow = true
				slimeball_projectile = true

			[light_sources.settings.entities.twilightforest]
				slider = true
				quest_ram = true
				death_tome = true
				kobold = true
				loyal_zombie = true
				redcap_sapper = true
				boar = true
				hydra = true
				lich = true
				thrown_wep = true
				hydra_mortar = true
				unstable_ice_core = true
				mist_wolf = true
				falling_ice = true
				dwarf_rabbit = true
				winter_wolf = true
				charm_effect = true
				fire_beetle = true
				carminite_golem = true
				helmet_crab = true
				lower_goblin_knight = true
				king_spider = true
				squirrel = true
				maze_slime = true
				moonworm_shot = true
				slime_blob = true
				ice_crystal = true
				lich_bolt = true
				tiny_bird = true
				ur_ghast = true
				yeti = true
				lich_bomb = true
				chain_block = true
				pinch_beetle = true
				rising_zombie = true
				deer = true
				harbinger_cube = true
				hedge_spider = true
				thrown_block = true
				lich_minion = true
				carminite_ghastguard = true
				skeleton_druid = true
				slime_beetle = true
				magic_painting = true
				seeker_arrow = true
				ice_snowball = true
				carminite_ghastling = true
				armored_giant = true
				minoshroom = true
				cube_of_annihilation = true
				blockchain_goblin = true
				knight_phantom = true
				swarm_spider = true
				carminite_broodling = true
				nature_bolt = true
				adherent = true
				raven = true
				redcap = true
				wand_bolt = true
				troll = true
				upper_goblin_knight = true
				hostile_wolf = true
				towerwood_borer = true
				chest_boat = true
				thrown_ice = true
				mosquito_swarm = true
				boat = true
				tome_bolt = true
				stable_ice_core = true
				plateau_boss = true
				ice_arrow = true
				protection_box = true
				minotaur = true
				wraith = true
				alpha_yeti = true
				giant_miner = true
				snow_queen = true
				roving_cube = true
				snow_guardian = true
				naga = true
				penguin = true
				bighorn_sheep = true

			[light_sources.settings.entities.betterend]
				dragonfly = true
				cubozoa = true
				shadow_walker = true
				end_slime = true
				silk_moth = true
				end_fish = true

			[light_sources.settings.entities.friendsandfoes]
				copper_golem = true
				glare = true
				player_illusion = true
				ice_chunk = true
				moobloom = true
				tuff_golem = true
				mauler = true
				iceologer = true
				wildfire = true
				crab = true
				rascal = true

			[light_sources.settings.entities.rediscovered]
				melee_pigman = true
				zombie_pigman = true
				thunder_cloud = true
				purple_arrow = true
				pylon_burst = true
				scarecrow = true
				dragon_pylon = true
				ranged_pigman = true
				red_dragon = true
				fish = true
				rana = true
				red_dragon_offspring = true
				bolt_ball = true
				steve = true
				pigman = true
				mountable_block = true
				beast_boy = true
				black_steve = true

			[light_sources.settings.entities.gravestone]
				player_ghost = true

			[light_sources.settings.entities.domesticationinnovation]
				highlighted_block = true
				feather = true
				recall_ball = true
				giant_bubble = true
				psychic_wall = true
				chain_lightning = true
				following_jukebox = true

			[light_sources.settings.entities.securitycraft]
				imsbomb = true
				securitycamera = true
				bouncingbetty = true
				bullet = true
				security_sea_boat = true
				sentry = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false
